# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'flix_codePath' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for flix_codePath
	pod 'Alamofire', '~> 4.7'
	pod 'AlamofireImage', '~> 3.3'
	pod 'GiFHUD-Swift'
	pod 'Gifu'
	pod 'PKHUD', '~> 5.0'

  target 'flix_codePathTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'flix_codePathUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
